config/routes.rb
Rails.application.routes.draw do
  root 'home#about'
  
  get 'home' => 'home#about'
  get 'upload' => 'file_upload#new'
  get 'report' => 'fsreports#show'
  

  resources :fsreports do 
    collection do 
      post :get_data , :as => :get_data 
    end
  end
  resources :file_upload do
      collection do
      post :show_data, :as => :show_data
      
    end   
  end

  

end

app/models/report.rb
class Report < ActiveRecord::Base
	serialize :failed_cases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/file_upload_controller.rb
require 'nokogiri'
require 'date'
class FileUploadController < ApplicationController
	
	
  	def new
 
	end
	def show_data
		#this part right here is just to make it work in heroku environment
		if Dir.exists?(Rails.root.join('upl'))
		else
			Dir.mkdir(Rails.root.join('upl'))
		end

 	 	@module_name = params[:module]
  		uploaded_io = params[:file]
  		@date = Date.strptime(params[:start_date],'%m/%d/%Y')
  		if @module_name and uploaded_io
  			@uploaded_file_name = uploaded_io.original_filename
  			
  			if uploaded_io.content_type == "text/html"
  
  				File.open(Rails.root.join('upl',  uploaded_io.original_filename), 'wb') do |file|
    				file.write(uploaded_io.read)
  				end
  			else 
  				flash.now[:error] = "Only supports html files, You sure you have the right report file from freshservice automation?"
  				render "new"
  				return false 
  			end

  			report_details = parse_file
  			if report_details.has_key?("failed_desc")
  				@errors = report_details["failed_desc"]
  			end
  			if !report_details.blank?
  				report = Report.new
	  			report.module = @module_name
	  		  	report.depdate = @date
	  			report.passed = report_details["pass"]
	  			report.failed = report_details["failed"]
	  			report.total = report_details["total_cases"]
	  			report.failed_cases = report_details["failed_desc"]
	  			report.save
	  			delete_uploaded_file
	  			render 'show'
  			else
  				render 'error'
  			end
  		else
  			render 'error'
  		end
	end



private
	def parse_file
		begin
			doc = Nokogiri::HTML(File.open(Rails.root.join('upl',@uploaded_file_name)))
			tables = doc.xpath("//table")[0]
			parsed = {}
			failed_desc =[]
			total_cases = 0
			tables.xpath("//tr").each do |t|
		
				if t.text.include?"PASSED"
					total_cases += 1
				elsif t.text.include?"FAILED"
					failed_desc << t.text.split("FAILED")
					total_cases += 1
				end
			end
			parsed["total_cases"] = total_cases
			parsed["failed"] = failed_desc.size
			parsed["pass"] = total_cases - failed_desc.size
			parsed["failed_desc"] = failed_desc
			return parsed
		rescue Exception => e 
			#remove_file
		end
	end
	def delete_uploaded_file
  		FileUtils.rm(Rails.root.join('upl',@uploaded_file_name))
	end


  

end

app/controllers/fsreports_controller.rb
require 'date'
class FsreportsController < ApplicationController
	
  def index
  	#@report_object = 
  end

  def get_data
  	@module = params[:module]
  	if @module
  		startdate = Date.strptime(params[:start_date],'%m/%d/%Y')
  		enddate = Date.strptime(params[:end_date],'%m/%d/%Y')
  		@error_message = String.new
  		if startdate <= enddate
  			if @module == "All"
  				@report_object = Report.where("depdate >= ? AND depdate <= ?", startdate,enddate)
  			else
  				@report_object = Report.where("module = ? AND depdate >= ? AND depdate <= ?", @module, startdate,enddate)
  			end
  			@passed = 0
  			@failed = 0
  			@failures = []
  			if !@report_object.blank?
  				@report_object.each do |rep|
  					@passed += rep.passed
  					@failed +=rep.failed
  					@failures << rep.failed_cases
  				end
  			else
  				@error_message = "There is no Data present for the selected Date Range. Please try again."
  				render 'error' 
  				return false
  			end
  		else
  			@error_message = "End Date cant be Smaller than Start date!"
  			render 'error' 
  			return false
  		end

  		render 'viewreport'
  	else
  		@error_message = "There is no Data present for the selected Module. Please try again."
  		render 'error' 
  		return false
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
	    base_title = "FS Reports"
	    if page_title.empty?
	      base_title
	    else
	      page_title + " | " + base_title
	    end
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/file_upload_helper.rb
module FileUploadHelper
end

app/helpers/fsreports_helper.rb
module FsreportsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_upload/error.html.erb
<% provide(:title, "Error") %>

<h2>There was an error saving the files retry again  </h2>
<label for="Link">Want to try Again?</label> <br>
<li><%= link_to "Upload",   upload_path %></li>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/file_upload/new.html.erb
<% provide(:title, "File Upload") %>
<div class="row">
<div class = "col-md-6 col-md-offset-3 ">
<%= form_tag url_for(:controller => 'file_upload', :action => 'show_data') , :multipart => true do %>
<%= label_tag 'Pick Module Name'  %>
 <%= select_tag 'module', options_for_select(["...","Admin","API","Changes","CMDB","Contracts","Dashboard","Elasticsearch","Problems","Releases","Reports","Solution","Tickets"], "...") ,class: 'form-control'%><br>

<%= label_tag 'Deployment Date' %><br>
<%= text_field_tag :start_date, Time.now.strftime("%m/%d/%Y") , class: 'form-control'%><br><br>
 <%= label_tag 'Attach File' %>
 
    <%= file_field_tag "file" ,  class: "form-control",required:'required'%><br><br>
  <%= submit_tag "Save", class: "btn btn-lg btn-primary" %><br>
<% end %>

</div>
</div>
<script type="text/javascript">
   $(document).ready(function(){
    $('#start_date').datepicker();
  });


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');



</script>

app/views/file_upload/show.html.erb
<% provide(:title, "Upload Succesful") %>
<div class="row">
<div class = "col-md-6 col-md-offset-3 ">
<h2> <%= @module_name %> Report File Saved Successfully<br>
Deployment Date: <%= @date %> <br>
</h2>
</div>
</div>
<h2> <%= @module_name %> Failed Cases </h2>
<table class="table" id="failuredata">
  <thead class="head-inverse">
    <tr>
      <th>TestCase</th>
      <th>Failure Reason</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
  <% if !@errors.blank? %>
    <% @errors.each do |error| %>
      <tr>
        <td><%= "#{error[0].gsub(/^[1234567890]*/, "")}" %></td>
          <td><%=  error[1] %> </td>
       </tr>
     <% end %>
     <%end %>
  </tbody>
</table>
<label for="Link">Want to upload another report?</label> <br>
<li><%= link_to "Upload",   upload_path %></li>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/fsreports/error.html.erb
<h2> OOPS! We have an error. It says <%= @error_message %> </h2>
<% provide(:title, "Error") %>
<label for="Link">Want to try Again?</label> <br>
<li><%= link_to "Reports",   report_path %></li>

app/views/fsreports/index.html.erb
<h1>Fsreports#index</h1>
<p>Find me in app/views/fsreports/index.html.erb</p>

app/views/fsreports/show.html.erb
<% provide(:title, "Reports") %>
<h1>Enter the details to fetch report</h1>
<div class="row">
<div class = "col-md-6 col-md-offset-3 ">
<%= form_tag url_for(:controller => 'fsreports', :action => 'get_data')  do %>
<label for="Module">Pick Module Name</label> <br>
 <%= select_tag 'module', options_for_select(["...","All","Admin","API","Changes","CMDB","Contracts","Dashboard","Elasticsearch","Problems","Releases","Reports","Solution","Tickets"], "...") ,class: 'form-control'%> <br>

<%= label_tag 'From Start Date'%>

 <%= text_field_tag :start_date, Time.now.strftime("%m/%d/%Y"), class: 'form-control' ,:required => true%><br><br>

 
  <%= label_tag 'End Date' %>
 <%= text_field_tag :end_date, Time.now.strftime("%m/%d/%Y") ,class: 'form-control',:required => true%><br><br>

  <%= submit_tag "Submit", class: "btn btn-lg btn-primary" %><br>
<% end %>

</div>
</div>

<script type="text/javascript">
   $(document).ready(function(){
    $('#start_date').datepicker();
    $('#end_date').datepicker();
  });


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');



</script>

app/views/fsreports/viewreport.html.erb
<% provide(:title, "Charts") %>
<div class="row">
<div class = "col-md-6 col-md-offset-3 ">
<h2> <%= @module%> Module Automation Report </h2>
<canvas id="myChart" width="200" height="200"></canvas><br><br>
</div>
</div>

<h2> <%= @module%> Module Failed Cases </h2>
<table class="table" id="failuredata">
  <thead class="head-inverse">
    <tr>
      <th>TestCase</th>
      <th>Failure Reason</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% if !@failures.blank? %>
    <% @failures.each do |error| %>
        <% error.each do |err| %>
      <tr>
        <td><%= "#{err[0].gsub(/^[1234567890]*/, "")}" %></td>
          <td><%=  err[1] %> </td>
       </tr>
     <% end %>
     <% end %>
     <% end %>
  </tbody>
</table>
<script>
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ["Failed <%=@failed%>", "Passed <%=@passed%>"],
        datasets: [{
            label: ' Rishabh',
            data: [<%=@failed%>, <%=@passed%>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)'
                
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)'
                
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});


  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');


</script>

app/views/home/about.html.erb
<% provide(:title,"Home") %>
<div class="center jumbotron">
  
<h2>
    Sign up for Freshservice @
    <a href="https://freshservice.com">FRESHSERVICE</a>
    
  </h2>
  

  </div>

<%= link_to image_tag("logo.png", alt: "Freshservice Logo"),
            'https://freshservice.com' %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90176354-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created 
    by <a href="https://in.linkedin.com/in/rishabhaditya">Rishabh</a>
  </small>
  <nav>
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Automation Dashboard", root_path , id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
             <li><%= link_to "Reports", report_path %></li>
             <li><%= link_to "Upload",   upload_path %></li>

        </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
       
    </div>

</body>
</html>